# Generated by Django 5.0.6 on 2025-02-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(blank=True, choices=[(10, '10 Q'), (50, '50 Q'), (100, '100 Q')], decimal_places=2, max_digits=10, null=True)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_receipt', models.FileField(upload_to='boletas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='images/')),
                ('publicar', models.BooleanField(blank=True, default=False)),
                ('fecha_creacion', models.DateField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.categoria')),
            ],
        ),
    ]
